insert into category values ('Open Male Recurve', 'Open Male', 'Recurve');
insert into category values ('Open Male Compound', 'Open Male', 'Compound');
insert into category values ('Open Male Barebow', 'Open Male', 'Barebow');
insert into category values ('Open Male Longbow', 'Open Male', 'Longbow');
insert into category values ('Open Female Recurve', 'Open Female', 'Recurve');
insert into category values ('Open Female Compound', 'Open Female', 'Compound');
insert into category values ('Open Female Barebow', 'Open Female', 'Barebow');
insert into category values ('Open Female Longbow', 'Open Female', 'Longbow');
insert into category values ('50+ Male Recurve', '50+ Male', 'Recurve');
insert into category values ('50+ Male Compound', '50+ Male', 'Compound');
insert into category values ('50+ Male Barebow', '50+ Male', 'Barebow');
insert into category values ('50+ Male Longbow', '50+ Male', 'Longbow');
insert into category values ('50+ Female Recurve', '50+ Female', 'Recurve');
insert into category values ('50+ Female Compound', '50+ Female', 'Compound');
insert into category values ('50+ Female Barebow', '50+ Female', 'Barebow');
insert into category values ('50+ Female Longbow', '50+ Female', 'Longbow');
insert into category values ('60+ Male Recurve', '60+ Male', 'Recurve');
insert into category values ('60+ Male Compound', '60+ Male', 'Compound');
insert into category values ('60+ Male Barebow', '60+ Male', 'Barebow');
insert into category values ('60+ Male Longbow', '60+ Male', 'Longbow');
insert into category values ('60+ Female Recurve', '60+ Female', 'Recurve');
insert into category values ('60+ Female Compound', '60+ Female', 'Compound');
insert into category values ('60+ Female Barebow', '60+ Female', 'Barebow');
insert into category values ('60+ Female Longbow', '60+ Female', 'Longbow');
insert into category values ('70+ Male Recurve', '70+ Male', 'Recurve');
insert into category values ('70+ Male Compound', '70+ Male', 'Compound');
insert into category values ('70+ Male Barebow', '70+ Male', 'Barebow');
insert into category values ('70+ Male Longbow', '70+ Male', 'Longbow');
insert into category values ('70+ Female Recurve', '70+ Female', 'Recurve');
insert into category values ('70+ Female Compound', '70+ Female', 'Compound');
insert into category values ('70+ Female Barebow', '70+ Female', 'Barebow');
insert into category values ('70+ Female Longbow', '70+ Female', 'Longbow');
insert into category values ('Under 21 Male Recurve', 'Under 21 Male', 'Recurve');
insert into category values ('Under 21 Male Compound', 'Under 21 Male', 'Compound');
insert into category values ('Under 21 Male Barebow', 'Under 21 Male', 'Barebow');
insert into category values ('Under 21 Male Longbow', 'Under 21 Male', 'Longbow');
insert into category values ('Under 21 Female Recurve', 'Under 21 Female', 'Recurve');
insert into category values ('Under 21 Female Compound', 'Under 21 Female', 'Compound');
insert into category values ('Under 21 Female Barebow', 'Under 21 Female', 'Barebow');
insert into category values ('Under 21 Female Longbow', 'Under 21 Female', 'Longbow');
insert into category values ('Under 18 Male Recurve', 'Under 18 Male', 'Recurve');
insert into category values ('Under 18 Male Compound', 'Under 18 Male', 'Compound');
insert into category values ('Under 18 Male Barebow', 'Under 18 Male', 'Barebow');
insert into category values ('Under 18 Male Longbow', 'Under 18 Male', 'Longbow');
insert into category values ('Under 18 Female Recurve', 'Under 18 Female', 'Recurve');
insert into category values ('Under 18 Female Compound', 'Under 18 Female', 'Compound');
insert into category values ('Under 18 Female Barebow', 'Under 18 Female', 'Barebow');
insert into category values ('Under 18 Female Longbow', 'Under 18 Female', 'Longbow');
insert into category values ('Under 16 Male Recurve', 'Under 16 Male', 'Recurve');
insert into category values ('Under 16 Male Compound', 'Under 16 Male', 'Compound');
insert into category values ('Under 16 Male Barebow', 'Under 16 Male', 'Barebow');
insert into category values ('Under 16 Male Longbow', 'Under 16 Male', 'Longbow');
insert into category values ('Under 16 Female Recurve', 'Under 16 Female', 'Recurve');
insert into category values ('Under 16 Female Compound', 'Under 16 Female', 'Compound');
insert into category values ('Under 16 Female Barebow', 'Under 16 Female', 'Barebow');
insert into category values ('Under 16 Female Longbow', 'Under 16 Female', 'Longbow');
insert into category values ('Under 14 Male Recurve', 'Under 14 Male', 'Recurve');
insert into category values ('Under 14 Male Compound', 'Under 14 Male', 'Compound');
insert into category values ('Under 14 Male Barebow', 'Under 14 Male', 'Barebow');
insert into category values ('Under 14 Male Longbow', 'Under 14 Male', 'Longbow');
insert into category values ('Under 14 Female Recurve', 'Under 14 Female', 'Recurve');
insert into category values ('Under 14 Female Compound', 'Under 14 Female', 'Compound');
insert into category values ('Under 14 Female Barebow', 'Under 14 Female', 'Barebow');
insert into category values ('Under 14 Female Longbow', 'Under 14 Female', 'Longbow');