insert into roundcategory values ('WA90/1440', 'Open Male Recurve');
insert into roundcategory values ('WA90/1440', 'Open Male Compound');
insert into roundcategory values ('WA90/1440', 'Under 21 Male Recurve');
insert into roundcategory values ('WA90/1440', 'Under 21 Male Compound');
insert into roundcategory values ('WA70/1440', 'Open Male Barebow');
insert into roundcategory values ('WA70/1440', 'Open Female Recurve');
insert into roundcategory values ('WA70/1440', 'Open Female Compound');
insert into roundcategory values ('WA70/1440', '50+ Male Recurve');
insert into roundcategory values ('WA70/1440', '50+ Male Compound');
insert into roundcategory values ('WA70/1440', 'Under 21 Male Barebow');
insert into roundcategory values ('WA70/1440', 'Under 21 Female Recurve');
insert into roundcategory values ('WA70/1440', 'Under 21 Female Compound');
insert into roundcategory values ('WA70/1440', 'Under 18 Male Recurve');
insert into roundcategory values ('WA70/1440', 'Under 18 Male Compound');
insert into roundcategory values ('WA60/1440', 'Open Male Longbow');
insert into roundcategory values ('WA60/1440', 'Open Female Barebow');
insert into roundcategory values ('WA60/1440', '50+ Male Barebow');
insert into roundcategory values ('WA60/1440', '50+ Female Recurve');
insert into roundcategory values ('WA60/1440', '50+ Female Compound');
insert into roundcategory values ('WA60/1440', '50+ Female Barebow');
insert into roundcategory values ('WA60/1440', '60+ Male Recurve');
insert into roundcategory values ('WA60/1440', '60+ Male Compound');
insert into roundcategory values ('WA60/1440', '60+ Male Barebow');
insert into roundcategory values ('WA60/1440', 'Under 21 Male Longbow');
insert into roundcategory values ('WA60/1440', 'Under 21 Female Barebow');
insert into roundcategory values ('WA60/1440', 'Under 18 Male Recurve');
insert into roundcategory values ('WA60/1440', 'Under 18 Male Compound');
insert into roundcategory values ('WA60/1440', 'Under 18 Male Barebow');
insert into roundcategory values ('WA60/1440', 'Under 18 Female Recurve');
insert into roundcategory values ('WA60/1440', 'Under 18 Female Compound');
insert into roundcategory values ('AA50/1440', 'Open Female Longbow');
insert into roundcategory values ('AA50/1440', '50+ Male Longbow');
insert into roundcategory values ('AA50/1440', '50+ Female Longbow');
insert into roundcategory values ('AA50/1440', '60+ Male Longbow');
insert into roundcategory values ('AA50/1440', '70+ Male Longbow');
insert into roundcategory values ('AA50/1440', '60+ Female Recurve');
insert into roundcategory values ('AA50/1440', '60+ Female Compound');
insert into roundcategory values ('AA50/1440', '60+ Female Barebow');
insert into roundcategory values ('AA50/1440', '60+ Female Longbow');
insert into roundcategory values ('AA50/1440', '70+ Female Recurve');
insert into roundcategory values ('AA50/1440', '70+ Female Compound');
insert into roundcategory values ('AA50/1440', '70+ Female Barebow');
insert into roundcategory values ('AA50/1440', '70+ Female Longbow');
insert into roundcategory values ('AA50/1440', 'Under 21 Female Longbow');
insert into roundcategory values ('AA50/1440', 'Under 18 Male Longbow');
insert into roundcategory values ('AA50/1440', 'Under 18 Female Barebow');
insert into roundcategory values ('AA50/1440', 'Under 18 Female Longbow');
insert into roundcategory values ('AA50/1440', 'Under 16 Male Recurve');
insert into roundcategory values ('AA50/1440', 'Under 16 Male Compound');
insert into roundcategory values ('AA50/1440', 'Under 16 Female Recurve');
insert into roundcategory values ('AA50/1440', 'Under 16 Female Compound');
insert into roundcategory values ('AA40/1440', 'Under 16 Male Barebow');
insert into roundcategory values ('AA40/1440', 'Under 16 Male Longbow');
insert into roundcategory values ('AA40/1440', 'Under 16 Female Barebow');
insert into roundcategory values ('AA40/1440', 'Under 16 Female Longbow');
insert into roundcategory values ('AA40/1440', 'Under 14 Male Recurve');
insert into roundcategory values ('AA40/1440', 'Under 14 Male Compound');
insert into roundcategory values ('AA40/1440', 'Under 14 Male Barebow');
insert into roundcategory values ('AA40/1440', 'Under 14 Male Longbow');
insert into roundcategory values ('AA40/1440', 'Under 14 Female Recurve');
insert into roundcategory values ('AA40/1440', 'Under 14 Female Compound');
insert into roundcategory values ('AA40/1440', 'Under 14 Female Barebow');
insert into roundcategory values ('AA40/1440', 'Under 14 Female Longbow');
insert into roundcategory values ('Sydney', 'Open Male Recurve');
insert into roundcategory values ('Sydney', 'Open Male Compound');
insert into roundcategory values ('Sydney', 'Open Female Recurve');
insert into roundcategory values ('Sydney', 'Open Female Compound');
insert into roundcategory values ('Sydney', '50+ Male Recurve');
insert into roundcategory values ('Sydney', '50+ Male Compound');
insert into roundcategory values ('Sydney', '50+ Female Recurve');
insert into roundcategory values ('Sydney', '50+ Female Compound');
insert into roundcategory values ('Sydney', 'Under 21 Male Recurve');
insert into roundcategory values ('Sydney', 'Under 21 Male Compound');
insert into roundcategory values ('Sydney', 'Under 21 Female Recurve');
insert into roundcategory values ('Sydney', 'Under 21 Female Compound');
insert into roundcategory values ('Brisbane', '60+ Male Recurve');
insert into roundcategory values ('Brisbane', '60+ Male Compound');
insert into roundcategory values ('Brisbane', '60+ Female Compound');
insert into roundcategory values ('Brisbane', '70+ Male Recurve');
insert into roundcategory values ('Brisbane', '70+ Male Compound');
insert into roundcategory values ('Brisbane', '70+ Female Compound');
insert into roundcategory values ('Brisbane', 'Under 18 Male Recurve');
insert into roundcategory values ('Brisbane', 'Under 18 Male Compound');
insert into roundcategory values ('Brisbane', 'Under 18 Female Recurve');
insert into roundcategory values ('Brisbane', 'Under 18 Female Compound');
insert into roundcategory values ('Adelaide', 'Open Male Compound');
insert into roundcategory values ('Adelaide', 'Open Female Compound');
insert into roundcategory values ('Adelaide', '50+ Male Compound');
insert into roundcategory values ('Adelaide', '50+ Female Compound');
insert into roundcategory values ('Adelaide', '60+ Male Compound');
insert into roundcategory values ('Adelaide', '60+ Female Compound');
insert into roundcategory values ('Adelaide', '70+ Male Compound');
insert into roundcategory values ('Adelaide', '70+ Female Compound');
insert into roundcategory values ('Adelaide', 'Under 21 Male Compound');
insert into roundcategory values ('Adelaide', 'Under 21 Female Compound');
insert into roundcategory values ('Adelaide', 'Under 18 Male Compound');
insert into roundcategory values ('Adelaide', 'Under 18 Female Compound');
insert into roundcategory values ('Melbourne', 'Open Male Barebow');
insert into roundcategory values ('Melbourne', 'Open Male Longbow');
insert into roundcategory values ('Melbourne', 'Open Female Barebow');
insert into roundcategory values ('Melbourne', 'Open Female Longbow');
insert into roundcategory values ('Melbourne', '50+ Male Recurve');
insert into roundcategory values ('Melbourne', '50+ Male Compound');
insert into roundcategory values ('Melbourne', '50+ Male Barebow');
insert into roundcategory values ('Melbourne', '50+ Male Longbow');
insert into roundcategory values ('Melbourne', '50+ Female Recurve');
insert into roundcategory values ('Melbourne', '50+ Female Compound');
insert into roundcategory values ('Melbourne', '50+ Female Barebow');
insert into roundcategory values ('Melbourne', '50+ Female Longbow');
insert into roundcategory values ('Melbourne', '60+ Male Recurve');
insert into roundcategory values ('Melbourne', '60+ Male Compound');
insert into roundcategory values ('Melbourne', '60+ Male Barebow');
insert into roundcategory values ('Melbourne', '60+ Male Longbow');
insert into roundcategory values ('Melbourne', '70+ Male Recurve');
insert into roundcategory values ('Melbourne', '70+ Male Compound');
insert into roundcategory values ('Melbourne', '70+ Male Barebow');
insert into roundcategory values ('Melbourne', '70+ Male Longbow');
insert into roundcategory values ('Melbourne', '60+ Female Barebow');
insert into roundcategory values ('Melbourne', '70+ Female Barebow');
insert into roundcategory values ('Melbourne', 'Under 21 Male Barebow');
insert into roundcategory values ('Melbourne', 'Under 21 Male Longbow');
insert into roundcategory values ('Melbourne', 'Under 21 Female Longbow');
insert into roundcategory values ('Melbourne', 'Under 18 Male Barebow');
insert into roundcategory values ('Melbourne', 'Under 18 Female Barebow');
insert into roundcategory values ('Perth', 'Under 16 Male Barebow');
insert into roundcategory values ('Perth', 'Under 16 Male Longbow');
insert into roundcategory values ('Perth', 'Under 16 Female Barebow');
insert into roundcategory values ('Perth', 'Under 16 Female Longbow');
insert into roundcategory values ('Perth', 'Under 14 Male Recurve');
insert into roundcategory values ('Perth', 'Under 14 Male Compound');
insert into roundcategory values ('Perth', 'Under 14 Male Barebow');
insert into roundcategory values ('Perth', 'Under 14 Male Longbow');
insert into roundcategory values ('Perth', 'Under 14 Female Recurve');
insert into roundcategory values ('Perth', 'Under 14 Female Compound');
insert into roundcategory values ('Perth', 'Under 14 Female Barebow');
insert into roundcategory values ('Perth', 'Under 14 Female Longbow');